

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: caijuyang

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql

file:
  path: /Users/JC/Downloads